service: pmb-plus-web-2

#frameworkVersion: "1.35.1"
plugins:
  - serverless-nextjs-plugin


provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  environment:
      SLS_DEBUG: true





package:
  exclude:
    - ./**

custom:
  serverless-nextjs:
    nextConfigDir: ./
    assetPrefix: 'https://s3.amazonaws.com/pmb-plus-web-2-dev-serverlessdeploymentbucket-1q2y8cmf4j11x'